// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxfWHH5aEv4-hTMW5GdYcH-o2ZDd8pbz0',
    appId: '1:670559204912:web:60d1cd5cecb7922ef41ff5',
    messagingSenderId: '670559204912',
    projectId: 'emahavitran',
    authDomain: 'emahavitran.firebaseapp.com',
    storageBucket: 'emahavitran.appspot.com',
    measurementId: 'G-716F25V9JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuOAf2ucxV8wGMBQ3cgDIG7QZ8IE5TrcE',
    appId: '1:670559204912:android:e02ea367203fa7fcf41ff5',
    messagingSenderId: '670559204912',
    projectId: 'emahavitran',
    storageBucket: 'emahavitran.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhcM6Bhu8GnLT2-VJpLCjnd-vN1zbzWRo',
    appId: '1:670559204912:ios:6b5cedaeb8a431ddf41ff5',
    messagingSenderId: '670559204912',
    projectId: 'emahavitran',
    storageBucket: 'emahavitran.appspot.com',
    iosClientId: '670559204912-inpmhu5m28pu6786dlnviv6nukcvu0ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.emahavitran',
  );
}
